(setq l2 '(vi (ge (ed hu ro) (vio (ka an) (lu al))) (rom el (mi va ne))))
(setq a (cadr l2))
(setq b (caddr l2))
(setq c (caddr a))
(setq d (caddr b))
(setq e (cadr c))
(setq c2 (list (car c) d))
(setq b2 (list (car b) e))
(setq a1 (list (car a) (cadr a) c2))
(setq l3 (list (car l2) a1 b2))