;(defun sph (l)
;( if (null (car l)) 0 
; (if(atom (car l))
;   (if (= (mod (car l) 2) 0)
;     ((+ (car l) (sph (cdr l))))
;     (sph (cdr l))
;     )
;   (sph (cdr l))
; )
;))

(defun sph (l)
( cond ((null (first l)) 0)
       ((atom (first l))
        ( cond ((= (mod (first l) 2) 0)
                (+ (first l) (sph (rest l))))
               (t (sph (rest l)))))
       (t (sph (rest l)))))